# Generated by Django 3.0 on 2019-12-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=150)),
                ('task_complete_date', models.DateField()),
                ('assigning_to', models.CharField(max_length=50)),
            ],
        ),
    ]
