# Generated by Django 3.0 on 2019-12-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_models',
            name='priority',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='task_models',
            name='task_assign_date',
            field=models.DateField(default=None),
        ),
    ]
