# Generated by Django 3.0 on 2019-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_app', '0002_auto_20191222_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Models_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=150)),
                ('task_assign_date', models.DateField(default=None)),
                ('task_complete_date', models.DateField()),
                ('assigning_to', models.CharField(max_length=50)),
                ('priority', models.CharField(default=None, max_length=50)),
                ('status', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
